name: generate tests
description: "This Action installs gocodeo for generating tests."
author: "Your Name <your.email@example.com>"

on:
  push:
    branches: [main]

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install gocodeo
        run: pip install gocodeo==0.0.0.15
