name: generate tests

on:
  workflow_dispatch:

jobs:
  generate-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install gocodeo
        run: pip install gocodeo==0.0.0.15
